// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-lHt9ksNct1YX77gdjh2NXcihX0CD-wQ',
    appId: '1:915470569535:web:4c5202474b26e141ace88a',
    messagingSenderId: '915470569535',
    projectId: 'petcare-a9915',
    authDomain: 'petcare-a9915.firebaseapp.com',
    storageBucket: 'petcare-a9915.firebasestorage.app',
    measurementId: 'G-PD1KQ91N97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASFzqNmpgMfoavS5Hx_5TVn2aPB-tT5Ew',
    appId: '1:915470569535:android:3a498556e14597b0ace88a',
    messagingSenderId: '915470569535',
    projectId: 'petcare-a9915',
    storageBucket: 'petcare-a9915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2maocAVQTOgnwayJGaq-u56d1j4cLWeg',
    appId: '1:915470569535:ios:0cb0216d1f53f2c4ace88a',
    messagingSenderId: '915470569535',
    projectId: 'petcare-a9915',
    storageBucket: 'petcare-a9915.firebasestorage.app',
    iosBundleId: 'com.example.userpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2maocAVQTOgnwayJGaq-u56d1j4cLWeg',
    appId: '1:915470569535:ios:0cb0216d1f53f2c4ace88a',
    messagingSenderId: '915470569535',
    projectId: 'petcare-a9915',
    storageBucket: 'petcare-a9915.firebasestorage.app',
    iosBundleId: 'com.example.userpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-lHt9ksNct1YX77gdjh2NXcihX0CD-wQ',
    appId: '1:915470569535:web:984e23071ae0649eace88a',
    messagingSenderId: '915470569535',
    projectId: 'petcare-a9915',
    authDomain: 'petcare-a9915.firebaseapp.com',
    storageBucket: 'petcare-a9915.firebasestorage.app',
    measurementId: 'G-LHKRZBVL5F',
  );
}
